from __future__ import annotations

import os

TEST_ENV = {
    "APP_MODE": "full",
    "MODEL": "gemini-2.5-flash",
    "EMBEDDING_MODEL": "text-embedding-005",
    "GOOGLE_CLOUD_PROJECT": "test-project",
    "REGION": "us-central1",
    "TOOLBOX_URL": "http://127.0.0.1:5000",
    "TOOLBOX_AUDIENCE": "http://127.0.0.1:5000",
    "BIGQUERY_MCP_URL": "https://bigquery.googleapis.com/mcp",
    "BIGQUERY_DATASET": "productivity_analytics",
    "BIGQUERY_ANALYTICS_PROCEDURE": "get_productivity_trends_v2",
    "ANALYTICS_BACKEND": "federated",
    "BIGQUERY_NATIVE_TVF": "productivity_trends_v3",
    "ANALYTICS_RETRY_ATTEMPTS": "3",
    "ANALYTICS_RETRY_BASE_SECONDS": "0",
    "ANALYTICS_RETRY_MAX_SECONDS": "0",
    "PSEUDONYMIZATION_KEY": "test-only-pseudonymization-key-00000000",
    "PRIVACY_RETENTION_DAYS": "90",
    "TAXONOMY_VERSION": "taxonomy_v1",
    "ROUTER_MAX_OUTPUT_TOKENS": "512",
    "ROUTER_THINKING_BUDGET": "0",
    "SPECIALIST_MAX_OUTPUT_TOKENS": "768",
    "SPECIALIST_THINKING_BUDGET": "0",
    "ANALYTICS_MAX_OUTPUT_TOKENS": "1024",
    "ANALYTICS_THINKING_BUDGET": "256",
    "ANALYTICS_MAX_RANGE_DAYS": "730",
    "ANALYTICS_QUERY_TIMEOUT_SECONDS": "30",
    "ANALYTICS_MAX_BYTES_BILLED": "1073741824",
    "AGENT_CONTEXT_MAX_EVENTS": "16",
    "MODEL_TEMPERATURE": "0.2",
    "DEFAULT_TIMEZONE": "Asia/Kolkata",
    "DEFAULT_PAGE_SIZE": "20",
    "LOG_LEVEL": "INFO",
    "STRUCTURED_LOGGING": "true",
    "ENABLE_REQUEST_LOGGING": "true",
    "REQUEST_ID_HEADER": "X-Request-ID",
    "AUTH_MODE": "disabled",
    "IDENTITY_PLATFORM_PROJECT_ID": "test-project",
    "IDENTITY_PLATFORM_TENANT_ID": "",
    "IDENTITY_TENANT_CLAIM": "app_tenant_id",
    "IDENTITY_ROLE_CLAIM": "app_role",
    "DEFAULT_TENANT_ID": "11111111-1111-4111-8111-111111111111",
    "DEMO_SUBJECT_ID": "22222222-2222-4222-8222-222222222222",
    "AUTH_CLOCK_SKEW_SECONDS": "30",
}

for key, value in TEST_ENV.items():
    os.environ.setdefault(key, value)
